
package com.mycompany.ecoactivistas.view;

import com.mycompany.ecoactivistas.controller.ProblemaActivistaController;


/**
 *
 * @author martinbl
 */
public class FrmProblemasActivistas extends javax.swing.JPanel {

    private ProblemaActivistaController paController;


    /**
     * Creates new form FrmProblemas
     */
    public FrmProblemasActivistas() {
        initComponents();
        paController = new ProblemaActivistaController();
        cargarProblemasActivistas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnFiltrarActivista = new javax.swing.JButton();
        btnFiltrarProblema = new javax.swing.JButton();
        scrlPanel = new javax.swing.JScrollPane();
        tblProblemasActivistas = new javax.swing.JTable();
        lblIDProblema = new javax.swing.JLabel();
        txtIDProblema = new javax.swing.JTextField();
        lblIDActivista = new javax.swing.JLabel();
        txtIDActivista = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Administración de Problemas Activistas");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 23, 788, -1));

        btnFiltrarActivista.setText("Filtrar por Activista");
        btnFiltrarActivista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActivistaActionPerformed(evt);
            }
        });
        add(btnFiltrarActivista, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 80, 190, -1));

        btnFiltrarProblema.setText("Filtrar por Problema");
        btnFiltrarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarProblemaActionPerformed(evt);
            }
        });
        add(btnFiltrarProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 80, 200, -1));

        tblProblemasActivistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProblemasActivistas.setDefaultEditor(Object.class, null);
        tblProblemasActivistas.getTableHeader().setReorderingAllowed(false);
        tblProblemasActivistas.setRowHeight(25);
        tblProblemasActivistas.setShowGrid(true);
        tblProblemasActivistas.setGridColor(java.awt.Color.LIGHT_GRAY);
        scrlPanel.setViewportView(tblProblemasActivistas);

        add(scrlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 109, 400, 314));

        lblIDProblema.setText("ID Problema");
        add(lblIDProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtIDProblema.setEditable(false);
        txtIDProblema.setEnabled(false);
        add(txtIDProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 40, -1));

        lblIDActivista.setText("ID Activista");
        add(lblIDActivista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtIDActivista.setEditable(false);
        txtIDActivista.setEnabled(false);
        add(txtIDActivista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 40, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 50));

        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, 50));

        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActivistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActivistaActionPerformed

    }//GEN-LAST:event_btnFiltrarActivistaActionPerformed

    private void btnFiltrarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarProblemaActionPerformed

    }//GEN-LAST:event_btnFiltrarProblemaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrarActivista;
    private javax.swing.JButton btnFiltrarProblema;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblIDActivista;
    private javax.swing.JLabel lblIDProblema;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrlPanel;
    private javax.swing.JTable tblProblemasActivistas;
    private javax.swing.JTextField txtIDActivista;
    private javax.swing.JTextField txtIDProblema;
    // End of variables declaration//GEN-END:variables
    private void cargarProblemasActivistas() {
        this.tblProblemasActivistas.setModel(paController.obtenerTablaProblemasActivistas());
    }

    private void guardarProblema() {
    }

    private void limpiarCampos() {
        txtIDActivista.setText("0");
        txtIDProblema.setText("0");
        btnGuardar.setText("GUARDAR");
    }

    private void cargarDatos() {
    }

    private void buscar() {
    }
}
